### ISSUE TITLE
Error on simulation

### ISSUE THREAD

**Issue by a5dur** [shaurya0406/ASAP7_FinFET_Inverter_Characterization#1]
Rookie here, need guidance please

osdi: no such command available in ngspice
osdi: no such command available in ngspice

Circuit: ** sch_path: /home/hussain/desktop/major project/asap7_finfet_inverter_characterization/xschem_asap7/inverter_ac.sch

Warning: unknown device type: n
Warning: unknown device type: n
Error on line 0 :
  n.x1.xnfet1.nnmos_finfet vout vin d b bsimcmg_osdi_n l=7e-009 nfin=13
 unknown device type - error 
    Simulation interrupted due to error!

![image](https://github.com/user-attachments/assets/a68119ba-0d1d-46a1-950e-9e1e31d16288)

**Comment by shaurya0406** [comment]
Seems like OSDI interface is not supported in your NGSpice installation. Try upgrading the NGSpice to v43+

**Comment by a5dur** [comment]
Worked! Thankyou :+1:
